### ISSUE TITLE
🐛 Everything native modifiers do not work

### ISSUE THREAD

**Issue by bropines** [lin-ycv/EverythingPowerToys#101]
**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [x] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**

**To Reproduce**
1. Activate PT Run
2. Enter a query consisting of two modifiers like `folder:wfn:rai`
3. No result (Everything works in the application, screenshot below)

**Expected behavior**
It displays everything as in the everything application

**Screenshots**
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/57861007/d5fbb40f-62fe-4687-9ece-b3605168f289)

**Version:**
 - PowerToy: 0.80.1
 - Everything: 1.4.1.1024 (x64)
 - EverythingPT: v0.80.0
 - Windows: 11 dev (22635.3570)

 **Installation method (How did you install the following softwares):**
 - PowerToys: Winget
 - Everything: Internet
 - EverythingPT: Winget

**Comment by lin-ycv** [comment]
@bropines whsat is `wfn:`? if it's a custom filter where did you define it?
if in Everything, you'd need to used 1.5a
if in `settings.toml`, this is a known bug #97 which has been fixed source, just not released yet, waiting for PT 0.81.

**Comment by lin-ycv** [comment]
You can test the fixed version here:
[Everything81alpha.zip](https://github.com/lin-ycv/EverythingPowerToys/files/15329828/Everything81alpha.zip)

*working with PT 0.80.1, but not guaranteeed to be compatible with PT 0.81.x

**Comment by lin-ycv** [comment]
new Version is published, this issues should now be fixed

**Comment by bropines** [comment]
> @bropines whsat is `wfn:`? if it's a custom filter where did you define it? if in Everything, you'd need to used 1.5a if in `settings.toml`, this is a known bug #97 which has been fixed source, just not released yet, waiting for PT 0.81.

Sorry. Git didn't notify me of your reply. I took it from the documentation [Everything](https://www.voidtools.com/en-us/support/everything/searching/)

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/57861007/daf4c966-b74e-4189-b9d6-354f6de166a0)

**Comment by lin-ycv** [comment]
that is the default behaviour, not sure why a filter/modifier is needed for that 
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/b239742a-ff51-4c12-8f48-366efcb57a19)

**Comment by bropines** [comment]
> that is the default behaviour, not sure why a filter/modifier is needed for that

I just needed to find at least one word that would be in the title and not contained in it. And this flag allows it to be done (now fn does what it does by default. Some fool wrote the documentation). Also, either I’m a fool, or the skis didn’t work

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/57861007/5fdec3ed-3a57-41aa-9baf-c18bbaa31e95)

**Comment by lin-ycv** [comment]
so the issue is that you've enabled regex and match patch, these options changes the behaviour and search paramemters, causing the modifier to not work correctly

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/70c25312-7edd-43c9-a9b2-1dfeac041c24)

test and let me know if it works, also v0.81.0 have some issues, i'd recommend you to revert back to 0.80.0 for now

**Comment by bropines** [comment]
Yep, work! Or maybe for such modifiers you can separately write a command like `m:` ?

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/57861007/dc68659e-2d13-4f1a-9d23-44d92ed20ffc)

**Comment by lin-ycv** [comment]
Read the explanation by void here, it's about match path and regex, but same concept applies here.
https://www.voidtools.com/forum/viewtopic.php?t=15092

So there not much I can do here, since the actual search is dealt by everything and not EPT

I could implement something like `m:wfn:` but I think that might start introducing weird behaviour different from everything. 
I think the best option is to have the same default settings as everything, so there aren't any confusions for users.
