### ISSUE TITLE
[Request] "Match path" enabled?

### ISSUE THREAD

**Issue by fhtdtdj** [lin-ycv/EverythingPowerToys#24]
Awesome plugin, thanks.

Could there be a way to have "Match Path" enabled?

In Everything with "Match Path" enabled, if you are searching for 123.txt in C:\ABC, you can quickly filter search for it by typing "12 AB"
In Run, typing 12 AB nullifies the search. Very useful to filter results if you have similar filenames in different paths...

Currently in Run, you have to manually prefix "path:" before any extra path parameter:, eg type "path:AB 12".

I managed to change the Everything_GetSort value since you added it in the Settings file, so perhaps this could also be added to the Settings file?

https://www.voidtools.com/support/everything/sdk/everything_getmatchpath/

**Comment by lin-ycv** [comment]
Has been added in the new release, it's in the PowerToys Run Settings window instead of settings file, since it's just a simple boolean option

**Comment by Coldblackice** [comment]
Thanks for adding this. Could I propose a better alternative, however? 

In Everything, instead of needing to enable "_Match Path_", one can instead preface a search term with a "\". Everything considers anything attached to "\" as a path, and it's even wildcard'able, e.g. `\*ytem32*\ *.exe` would find all .EXE's in \System32.

I realize the purpose of this plugin probably isn't to replace all that Everything can do, but rather as a quick/general catch-all search for general use. But I feel the addition of path-matching via a "\" would be utmost useful, enabling a quick and simple way of distinguishing between paths and files when searching.
