### ISSUE TITLE
Have folders show up in search results

### ISSUE THREAD

**Issue by aagha** [lin-ycv/EverythingPowerToys#26]
**Is your feature request related to a problem? Please describe.**
When searching, EverythingPowerToys returns file results, but not folders.

**Describe the solution you'd like**
Search a folder name and have that folder name show up in the results.

**Describe alternatives you've considered**
I use the Everything app to find a folder if I need to find its contents.

**Additional context**
Should be able to search "Downloads" and have that come up in the search results with PowerToys Run
![image](https://user-images.githubusercontent.com/5522103/194919468-b41da106-9cd9-487f-b0cc-28acf6ab50cf.png)

**Comment by lin-ycv** [comment]
It does return folder results:
![image](https://user-images.githubusercontent.com/60565737/195250537-b5bf0848-d119-4da8-af15-e08c99ea7c1e.png)

The issue is how the sorted result is returned, by default, the sort is `modified descending`, since it's unlikely you modify the folder name, other files are being returned first.

you can change the sort method in `settings.toml` accordingly
![image](https://user-images.githubusercontent.com/60565737/195251186-efe64585-dffb-4cea-a51a-b32cbdd80400.png)

alternatively, user the `folder:` filter, which will limit search to folder names.
![image](https://user-images.githubusercontent.com/60565737/195251289-a72f8595-6572-4cd7-90df-e7d06d094016.png)

**Comment by aagha** [comment]
Never mind... it says at the bottom of the page:

![image](https://user-images.githubusercontent.com/5522103/195479853-a4216392-3c2c-48ba-ad89-ec294903f2c2.png)
