### ISSUE TITLE
[BUG] UI glitch occurs if the input filename is longer than search box

### ISSUE THREAD

**Issue by airium** [lin-ycv/EverythingPowerToys#28]
**Describe the bug**
UI glitch occurs if the input filename is longer than search box.

**To Reproduce**
When the input filename is shorter than the search box, the completion suggestion works fine:
![img1](https://user-images.githubusercontent.com/38249940/200051303-27c06300-5368-41ef-8782-9c7b2428c40f.png)

However once the filename exceeds the length of the search box, auto-completion text is positioned incorrectly and interleave with search text, making the text difficult to read:
![img2](https://user-images.githubusercontent.com/38249940/200051329-abb70dbf-e8cb-4989-a2d6-d6047fd7edb7.png)

**Expected behavior**
1. the auto-completion text should be placed correctly - a fix is expected.
2. or add a toggle allowing the user to enable/disable auto-completion from Everything Plugin.

**Logs (please upload or provide link to you log):**
Log should not matter.

**Version (please provide the version of software you are using):**
 - Everything Plugin: 0.58-0.64 (the latest)
 - PowerToy: 0.62-0.64 (I can't remember before 0.62, so at least since 0.62)
 - Everything: V1.4.1.1022 (x64)
 - Windows: Windows 10 21H2/22H2

**Additional context**
Everything Plugin 0.56.2 or earlier version has no such issue as these old versions provides no auto-completion.

**Comment by lin-ycv** [comment]
There's not much I can do here, it's not a plugin specific issue, but a PowerToys Run issue, this also happens when not using this plugin
![image](https://user-images.githubusercontent.com/60565737/200110059-66366244-ba31-4595-b574-a986647c74c4.png)

I do not have control over how PTR does autocompletion, I recommend you to raise this issue on [PowerToys Repo](https://github.com/microsoft/PowerToys/issues)

**Comment by airium** [comment]
Thank you for the explanation. I thought so.
