### ISSUE TITLE
[Request] Copy file instead of path - change Ctrl+C to copy the file instead of copying the file path

### ISSUE THREAD

**Issue by daniel-richter** [lin-ycv/EverythingPowerToys#34]
**Is your feature request related to a problem? Please describe.**
Currently, there is an context menu item "Copy path to clipboard" associated with Ctrl+C. There were only a few scenarios where I need the path of a found file. Instead I tend to use the file itself. 
Adding an option to copy the file instead of copying the file path to the clipboard would be a solution (or feasible workaround) for https://github.com/microsoft/PowerToys/issues/4462. Changing the default behaviour of the Ctrl+C to that would solve https://github.com/microsoft/PowerToys/issues/13006

**Describe the solution you'd like**
Currently, copy the file's path to the clipboard is implemented as follows:
https://github.com/lin-ycv/EverythingPowerToys/blob/f0372aa625e74a9507ba89921f5fac76d374326d/ContextMenuLoader.cs#L63

Changing that line as follows would copy the complete file.
```csharp
Clipboard.SetData(DataFormats.FileDrop, new string[] { record.Path });
```

Since "copy path to clipboard" is still a useful feature (but maybe not as default), an additional ContextMenuResult would be required.

**Describe alternatives you've considered**
Use the context menu item "open containing folder" and copy/drag&drop the file would solve the problem, too. But that is too many unnecessary steps.

**Comment by lin-ycv** [comment]
That's a good idea, I can implement copy file. Will take some time to figure out the best implementation tho, don't want the shortcut exp to be too different from PowerToys defaults. 
 
But I'm not sure drag would be possible to implement from the plugin, that'd be something PowerToys need to implement.

**Comment by lin-ycv** [comment]
So I think implementing it as a toggle and keeping both functions is the best way forward `Ctrl+C` and `Ctrl+Alt+C` (Default will be copy path to be consistent with PowerTyos defaults)
![image](https://user-images.githubusercontent.com/60565737/204866191-a303ce1c-095e-4370-a1de-bc8a15c4a47b.png)
![image](https://user-images.githubusercontent.com/60565737/204866506-9c48dcfe-a13d-496d-bbc9-3331bd03f4c3.png)

@daniel-richter since you recommended the feature, you can choose the new icon for copy path, 
folderSelect (Left) OR link (Right) 
![image](https://user-images.githubusercontent.com/60565737/204867646-bee5de1d-cdb6-4962-b79e-4a980e9121fb.png)
or do you think the copy icon should be kept for copy path, and copy file/folder needs a new icon (to be consistent with PowerToys default)?

**Comment by daniel-richter** [comment]
In my opinion the _link_ [icon](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font) is better for copy path. In my mental model a file item in the result list is somewhat like an item in the Windows Explorer file list - copying there puts the whole file to the clipboard; so the _copy_ icon should copy the file/folder. Btw.: The Explorer's icon for "copy path" is `\\...`

The settings text could be more specific - like "Copy file/folder instead of path | Change Ctrl+C behaviour".

**Comment by lin-ycv** [comment]
`\\..` would be my first choice, but that's not an icon available in Segoe, and using it as plain text gets cut off since it's wider than it is tall.

I've thought about using folderHorizontal, but It's confusing with folderOpen
![image](https://user-images.githubusercontent.com/60565737/204965913-8e9bc8de-37c7-438c-a574-8c50f9c28de8.png)

I'll finalize it with link.
