### ISSUE TITLE
Incorrect file icons shown

### ISSUE THREAD

**Issue by N6MCA51593** [lin-ycv/EverythingPowerToys#47]
**Describe the bug**
Search results often have generic file type icons attached to them. For me, it always happens with .lnk files and media files associated with MPC-HC and Windows Photo Viewer. It's problematic because Windows creates a lot of .lnk files for the benefit of the task view file history, and it's impossible to tell those links from the actual files without glancing at the full path and file name.

**Expected behavior**
.lnk files should have icons that represent their file type with a little arrow attached to them, media files should have the player icon. This is the way it is done in Everything. I'm not sure if the regular Windows search shows those link files, perhaps it's even better to drop them from search results altogether or downgrade them in sorting rankings if possible.  

**Screenshots**
Everything:
![img-2023-03-02-01-50-24](https://user-images.githubusercontent.com/54366461/222283407-40013231-fba8-4ce0-ad49-834cd9b56918.png)
Powertoys Everything:
![Untitled00-2](https://user-images.githubusercontent.com/54366461/222286364-1561ce2a-d93a-4252-8337-78a53e869536.jpg)

**Version (please provide the version of software you are using):**
 - PowerToys: 0.67.1 (EverythingPowerToys v0.66)
 - Everything: 1.4.1.1022
 - Windows: Windows 10 x64 22H2

**Comment by lin-ycv** [comment]
This isn't something I can fix, I've looked into this previously, but there's no reasonable solution for it.
I recommend turning on the `preview` option in Powertoys settings if you find this a big issue.

This cannot be fixed because of how powertoys run works, it expects an image path for the icon, but a lot of time, icon files are part of a resource dll file and not a standalone image. This is why you get a generic icon; it shows the icon of that dll file.

By turning on `preview` option, the plugin instructs powertoys to get the file, which will cause window/file explorer to return the thumbnail. 
Icon preview option isn't turned on by default because of non-local files, like online files in dropbox, google drive, onedrive...etc.
In previous tests, trying to preview (get the thumbnail) will start the file download, which may slow down results depending on the file size and internet speed.
