### ISSUE TITLE
[BUG] Results disappear after every new character

### ISSUE THREAD

**Issue by gisturbance** [lin-ycv/EverythingPowerToys#58]
**Describe the bug**
See https://github.com/lin-ycv/EverythingPowerToys/issues/36.

With Powertoys 0.73.0 the issue should've been fixed, though some plugins still cause flickering upon typing, like Everything.
https://github.com/microsoft/PowerToys/issues/22490#issuecomment-1729733250

It might be necessary to adjust some lines of code.

**Version (please provide the version of software you are using):**
 - PowerToys: 0.73.0
 - Everything: 1.5.0.1356a
 - Windows: Windows 11 Pro 22H2 22621.2283

**Comment by lin-ycv** [comment]
this is something you can set in the powertoys run settings, turn on input smoothing and add a delay for immediate plugins, it will cause run to wait for a bit before sending the query to the plugins, so the results will not flash in and out.
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/1a16e3e5-d2af-4dd2-bb73-3b1538f1c55d)

However, the expected behaviour of 
> When results are found, the results list should not disappear
is not something that has been changed/fixed in 0.73.0?

**Comment by gisturbance** [comment]
The delay changes nothing using any value from `0` to `50` for Everything. Plugins like Programs, Services, URI-Handler, Web Search and others don't flicker even at `0`.

It seems strange to me that implementation-wise a delay is thought necessary - haven't looked at the implementation though -, instead of keeping the current UI until the results come back.

**Comment by lin-ycv** [comment]
@gisturbance I don't think I'm understanding your issue correctly. I'm on PT v0.74.0
I don't see any behaviour difference in terms of flickering between search and everything

As seen here, the search results also flickers in and out:
![Animation](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/4f1ba440-9398-48d7-b779-e53c5adcbcc0)

Can you provide some screen recordings of what the difference you've seeing is?
