### ISSUE TITLE
Installation process?

### ISSUE THREAD

**Issue by onespecies** [lin-ycv/EverythingPowerToys#6]
Hi, i'm new to Github, sorry if i'm doing anything wrong.

I tried following the instructions in your readme file, but did not see any improvements in the search of the powertoys run. Am i missing some steps that might be implicit? Do i need to install something, restart something? tweak some settings in the Everything program, for this to work? i only did what is written in the readme file; i downloaded the Everything program and installed it, i downloaded your repo and extracted the whole folder into the right folder and nothing else.

Again, sorry if this query landed in the wrong place.

**Comment by lin-ycv** [comment]
Hi, nothing wrong with asking a question.

Once you've extracted the downloaded folder and installed Everything, you'll need to **restart PowerToys** so that it loads the plugin.
Once you've restarted PowerToys, check to see you have the plugin enabled
![image](https://user-images.githubusercontent.com/60565737/158924631-1683e19c-71b3-436f-b546-d6a75311ae3a.png)

If it's enabled, you should see search results in PT Run.
![image](https://user-images.githubusercontent.com/60565737/158925102-5997fa6f-0d80-401a-b9fe-eb1bf62db271.png)


If not, check your everything setting, make sure it's indexing the drive/folder you want to search, and that it's being included in the Everything database.
![image](https://user-images.githubusercontent.com/60565737/158924886-d672b9ad-816f-4b00-b42d-9bc4b475bd8b.png)

**Comment by onespecies** [comment]
Hello again,
Thanks for the answer and your time, i appreciate it.
I restarted PT first by exiting it and killing any process linked to it and starting it and afterwards by restarting my laptop. Nothing new, it does not show up in the plugins screen.

Plugins screen where i search for everything:
![image](https://user-images.githubusercontent.com/101830487/158951497-5dd8b333-ae1c-49e7-b4f0-bf093d7101e0.png)

PT plugins folder:
![image](https://user-images.githubusercontent.com/101830487/158951677-4de88555-2691-43c4-8f73-eeca63e8f179.png)

Everything index settings:
![image](https://user-images.githubusercontent.com/101830487/158951846-f3878dba-24c7-4cb2-8354-5b6b1961f843.png)

Sorry for the inconvenience, i have the impression i must be doing something completely wrong if everyone else has been able to make it work with just the information in the readme file.

**Comment by lin-ycv** [comment]
> PT plugins folder:
> ![image](https://user-images.githubusercontent.com/101830487/158951677-4de88555-2691-43c4-8f73-eeca63e8f179.png)

You've downloaded the repo, the repo is uncompiled code, it won't run.
The repo is for those that want to tinker with the code/look over the code.

You should download the zip file in the release section:
https://github.com/lin-ycv/EverythingPowerToys/releases
![image](https://user-images.githubusercontent.com/60565737/158966545-dd74165f-4f0f-4f7f-ae65-60d0968524bf.png)
![image](https://user-images.githubusercontent.com/60565737/158966786-d72395d5-38f6-4f58-8751-a02fc00d45a5.png)

This should solve your issue.

**Comment by onespecies** [comment]
Thank you!
