### ISSUE TITLE
Please help [BUG] 

### ISSUE THREAD

**Issue by hocy1609** [lin-ycv/EverythingPowerToys#74]
**Describe the bug**
Everything is not running

**Screenshots**
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/74152095/3f20a033-3103-446e-992b-b2cc3fe6f93d)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/74152095/845270a7-5cec-48aa-a068-034d0dae5827)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/74152095/5b0261ad-1fb4-4c8e-9830-794a33693a70)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/74152095/8433b0e7-c211-4dd7-8f08-b0cc9e8bfe89)

**Logs (please upload or provide link to you log):**
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs
[2024-01-11.txt](https://github.com/lin-ycv/EverythingPowerToys/files/13907315/2024-01-11.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: win store latest
 - Everything: 1.5a
 - Windows: 11 23h2

**Comment by dexeonify** [comment]
It's rare to see others trying to make Everything 1.5a work with PowerToys Run, but it's unfortunate that this issue was closed without any explanation. Anyways, in case others are also in this predicament:
1. The instruction in the README about [disabling 1.5a instance](http://www.voidtools.com/forum/viewtopic.php?f=12&t=9799#instance) is **inadequate or outdated**.
2. To prevent confusion, I would recommend **uninstalling** Everything 1.4 and only keep Everything 1.5a installed. (With this config, only 1 Everything instance can run anyways)
I can assure you that Everything 1.5a works with this plugin. (I'm currently using it)
3. Follow this [instruction](https://www.voidtools.com/forum/viewtopic.php?p=36726#p36726) instead. Ok, maybe not all of them, I will highlight the important part:
> - Completely exit Everything 1.5 (right click the Everything 1.5 system tray icon and click Exit)
> ...
> - _[snip]_ You **don't need to** rename the Everything 1.5 folder to Everything
> ...
> - Create an empty file in `C:\Program Files\Everything 1.5a` with the following filename:
> `NO_ALPHA_INSTANCE`
> - An easy way to do this is to open Notepad from the Start menu (right click notepad and click Run as an administrator):
> - In Notepad, from the File menu, click Save.
> - Change Save as type to: All Files (*.*)
> - Browse to your Everything 1.5 installation folder (`C:\Program Files\Everything 1.5a`)
> - Change the Filename to: `NO_ALPHA_INSTANCE`
> - Click Save.
4. With this `NO_ALPHA_INSTANCE` file, you don't have to worry about setting `alpha_instance=0` in the config file. [See here](https://www.voidtools.com/forum/viewtopic.php?p=42848#p42848).
Personally, I could never get `alpha_instance=0` to work. I've tried with both the `Everything.ini` file in `Program Files` and `%APPDATA%`). 
5. Finally, restart/reinstall the Everything service.
> - Uninstall the Everything Service:
> - In Everything 1.5a, from the Tools menu, click Options.
> - Click the General tab on the left.
> - Uncheck Everything Service
> - Maybe exit and restart the Everything instance for safety
> - Go to the same menu and enable Everything Service. It should prompt you to install the service.
6. Verify in Task Manager that the Everything service is running. Ensure it's just called "Everything" and not "Everything 1.5a". You may have to restart PowerToys to get Everything results.

Honestly, all these are worth the hassle if you consider the [feature set of Everything 1.5 Alpha](https://www.voidtools.com/forum/viewtopic.php?t=9787). It doesn't seem like a new release is on the horizon despite being in Beta **for years**.

**Comment by lin-ycv** [comment]
A FYI for those using 1.5a, there are some "bugs/issues" with the sdk when using 1.5a
For example, the run count is incremented but not save, once the 1.5a instance is exited, the run count is reverted back.
From what's I've tested, simple queries seems to work just fine, but some features may not be working properly, use at your own discretion.

**Comment by jyc001** [comment]
Well, there is a simple way to disable the alpha instance without editing or creating any file manually.

1. First open the main window of everything then click the **Tools** (on the toolbar) **- Options** or you can JUST PRESS Ctrl-P instead.
 ![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/7eed0ba6-5183-43ff-a0ae-b50013c24e93)
2. Then navigate to the **advanced** section 
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/8ccbec45-ba38-43c1-b980-7e400b2c12a2)
3. Next make sure the **show only modified settings** is not selected
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/005657de-d4a2-45cd-9d64-f82cc2c2fb74)
4. then type **alpha_instance** (or maybe just alpha)  in the input section next to the **Show settings containing:**
 ![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/f2abf88e-5be9-474a-8ffd-dc1085dca834)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/5de8c43d-86df-4cdc-944b-d53dbe937475)
5.Then click on the **alpha_instance** line in the tableView to make it to be activated.
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/fbaf7aff-c380-49bd-a4d1-fc7c2576ebb1)
6. Last press the **true** on the section **Value of alpha_instance** which is just under the tableView.
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/040a418c-7177-42fa-8539-91454b63d183)
7.Finally.press **OK**(and **Apply** if you want) and **COMPLETELY RESTART** the **Everything** and the **PowerToys** ,(If you don't know how to do, just restart the copmputer)
Then you will be able to use the EverythingPowerToys plugins.

**Comment by dexeonify** [comment]
That's a very detailed guide, if I've ever seen one (perhaps too thorough on the option page). However, I end up having the same problem as the instructions in README:
- The **Everything UI** runs with no_alpha_instance, as evident from the title bar displaying only "Everything" instead of "Everything (1.5a)"
- Despite reinstalling the Everything service multiple times (_following my step 5 above_), the Everything service still lists as "Everything 1.5" in Task Manager

> COMPLETELY RESTART the Everything

Perhaps you could elaborate more on this? Is restarting the Everything UI _and_ the service insufficient? Maybe I do really need to restart the computer. In this case, my method doesn't require restarting the PC. ;) I invite others to test as well.

**Comment by jyc001** [comment]
> That's a very detailed guide, if I've ever seen one (perhaps too thorough on the option page). However, I end up having the same problem as the instructions in README:
> 
> * The **Everything UI** runs with no_alpha_instance, as evident from the title bar displaying only "Everything" instead of "Everything (1.5a)"
> * Despite reinstalling the Everything service multiple times (_following my step 5 above_), the Everything service still lists as "Everything 1.5" in Task Manager
> 
> > COMPLETELY RESTART the Everything
> 
> Perhaps you could elaborate more on this? Is restarting the Everything UI _and_ the service insufficient? Maybe I do really need to restart the computer. In this case, my method doesn't require restarting the PC. ;) I invite others to test as well.

right on my computer i just need to click **File-Exit**(in the picture **文件-退出**)(or just **Ctrl+Shift+Q) and then reopen everything (not even need to restart the powertoys) then the EverythingPowertoys plugins successfully connect to the instance and work properly.
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60777728/015a0756-8331-4eee-a659-51ab2c72e2a9)

**Comment by e-t-l** [comment]
> Follow this instruction instead. Ok, maybe not all of them, I will highlight the important part

I followed your instructions, and after creating the NO_ALPHA_INSTANCE file and restarting the Everything process and service, I have lost all my configuration data for Everything. It does not remember any of my settings, including custom filters, search parameters, default window size, keyboard shortcuts, or anything. Do you know why that happened or how to get them back?

**Comment by dexeonify** [comment]
No need to panic. Your data is still there, it's just that Everything doesn't recognise the "old" filename. Simply delete the NO_ALPHA_INSTANCE file again and restart Everything. I will suggest trying @jyc001's steps first though.

**Comment by GollyJer** [comment]
> there is a video for all my steps [video link](https://youtu.be/R7j8RhCW96I)

This is the way. Thank you!

**Comment by Uddhav07** [comment]
> there is a video for all my steps [video link](https://youtu.be/R7j8RhCW96I)

ok

**Comment by 006lp** [comment]
Be careful not to enable the two checkboxes "Run as administrator" and "Run indexing process as administrator" in the options of Everthing. I found that I couldn't use them because I enabled these two, but it worked fine after I turned them off.

**Comment by lin-ycv** [comment]
> Be careful not to enable the two checkboxes `Run as administrator` and `Run indexing process as administrator` in the options of `Everthing` . I found that I couldn't use them because I enabled these two, but it worked fine after I turned them off.

I think this comes down to what privileges you're running powertoys with, if powertoys isn't running with admin privileges, it can't access/call on things that have admin privileges.

**Comment by hawchou1995** [comment]
> 别把 Everything 设置里的“以管理员身份运行”和“以管理员身份运行索引服务”两个勾都打上。我勾了就用不了，关掉立马正常。

感谢，看到这里解决了冲突的问题
