### ISSUE TITLE
[BUG] "folder:" filter doesn't work when enable RegEx|"folder:"筛选命令在启用正则搜索后失效

### ISSUE THREAD

**Issue by Jiang10086** [lin-ycv/EverythingPowerToys#96]
**Describe the bug**
When I enable RegEx in the plugin's setting, I can't use "folder:" commander to filter only folders.

**To Reproduce**
1. Enable RegEx in plugin's setting
2. Search use "folder:"
3. No result shows

**Expected behavior**
"folder:" still work in RegEx mode.

**Screenshots**
When RegEx disabled:
![image](https://GitHub.com/lin-ycv/EverythingPowerToys/assets/67213568/28a2f107-5b89-4593-b60d-e40c187386c6)

When RegEx enabled:
![image](https://GitHub.com/lin-ycv/EverythingPowerToys/assets/67213568/3a14136f-fade-43bb-8519-687fdf73d462)

**Logs (please upload or provide link to you log):**
[2024-04-28.txt](https://github.com/lin-ycv/EverythingPowerToys/files/15142466/2024-04-28.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.80.1
 - Everything:1.4.1.1024 (x64)
 - Windows: Windows 11 Pro Workstaion 23H2 22631.3527

**Comment by lin-ycv** [comment]
this isn't a bug per say, at least not with this plugin, it's a issue with Everything not supporting search filters when regex is enabled

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/bae7a57a-6cab-4966-98cf-d334c34de286)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/f68b88c6-14e9-4b4a-9f35-6b2734b2ae3e)

what you can do alternatively is enable `regex:` in the search query instead of the settings
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/6226f294-4e96-4f5b-9f88-b5d0c3316bf6)

this however made me notice that search filters are broken in the latest release #97
